config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'order_products/create'
  get 'order_products/update'
  get 'order_products/destroy'
  get 'carts/show'
  resources :pages
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'orders/index'
  # get 'orders/show'
  # get 'customers/index'
  # get 'customers/show'
  # get 'categories/index'
  # get 'categories/show'
  # get 'products/index'
  # get 'products/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # create the index and show restful routes
  resources :products, only: %i[index show]
  resources :customers, only: %i[index show]
  resources :orders, only: %i[index show]
  resources :categories, only: %i[index show]

  resource :cart, only: [:show]
  resources :order_products, only: %i[create update destroy]

  get 'search_results', to: 'search#results', as: 'search_results' # route for seach results
  get 'static/:permalink', to: 'pages#static', as: 'static'
  root to: 'products#index' # root to products controller index action
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  has_many :orders


  validates :name, :email, :address, presence: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_products
  has_many :products, through: :order_products
  before_validation :set_order_status, on: :create
  # before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_products.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_product.rb
# frozen_string_literal: true

class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product # creates correspding FK in the product table

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def product_present
    errors.add(:product, 'is not valid or is not active.') if product.nil?
  end

  def order_present
    errors.add(:order, 'is not a valid order.') if order.nil?
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category

  has_many :order_products
  has_many :orders, through: :order_products

  validates :name, :price, :description, presence: true
  validates :price, numericality: true

  mount_uploader :image, ImageUploader

  # displays product with active status. So esentially , in stock.
  default_scope { where(active: true) }
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
    @order_products = current_order.order_products
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def index
    @order = Order.order(:date)
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  before_action :set_page, only: %i[show edit update destroy]

  # THE REQUIRED ACTION FOR about-us STATIC PAGE
  # this is shared with the view we had to create. in this case static.html.erb(in pages views)
  def static
    @page = Page.find_by(permalink: params[:permalink])

    redirect_to root_path if @page.nil?
  end

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show; end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_products.sum(:quantity)} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CanCorp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%# this below was dded for shopping cart %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <% if request.ssl? %>
      <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <% else %>
      <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
      <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <% end %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
   <header class="navbar navbar-expand-md bg-dark navbar-dark">
      <h1 class ='mh1'> Welcome To CanCorp </h1>

        <nav class="navbar navbar-expand-md bg-dark navbar-dark">

          <!-- Toggler/collapsibe Button -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>

          <!-- Navbar links -->
          <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to 'Home', root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Products', products_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Categories', categories_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'About Us', static_path(permalink: 'about-us'),class: 'nav-link'  %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
          </div>
        </nav>
    </header>

						    <%= form_tag(search_results_path, method: "get") do %>
						      <%= label_tag(:query, "Search for:") %>
						      <%= text_field_tag(:query) %>
                  <%= select_tag(:queryc, options_for_select(Category.all.map{|cat| [cat.name, cat.id]})) %>
						      <%= submit_tag("Search") %>
						    <% end %>
<br><br>

  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1 class='mh1'><%= link_to "My Store", root_path %></h1>
          <h4 class='mh4'> Categories </h4>
            <ul>
            <% Category.all.each do |category| %>
              <li class = 'catList' ><%= link_to category.name, category %> </li>
            <% end %>
            </ul>
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    </div>
    <br>



    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/static.html.erb
<h1> <%=@page.title%> </h1>

<p> <%= @page.content%> </p>


<p> <%= @page.permalink%> </p>